package com.slh.app

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import org.json.JSONArray
import org.json.JSONObject
import java.nio.charset.StandardCharsets
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

object SLHLocalStorage {

    // =========================================================
    // CONSTANTS
    // =========================================================

    private const val PREF_NAME =
        "slh_secure_storage"

    private const val KEYSTORE =
        "AndroidKeyStore"

    private const val KEY_ALIAS =
        "SLH_LOCAL_DATA_KEY"

    private const val TRANSFORMATION =
        "AES/GCM/NoPadding"

    private const val GCM_TAG_LENGTH =
        128

    private const val IV_LENGTH =
        12

    // =========================================================
    // STORAGE KEYS
    // =========================================================

    private const val STUDENTS_KEY =
        "students_data"

    private const val BATCHES_KEY =
        "batches_data"

    private const val USERS_KEY =
        "users_data"

    private const val COACHING_PROFILES_KEY =
        "coaching_profiles_data"

    private const val PAYMENTS_KEY =
        "payments_data"

    private const val FEE_PLANS_KEY =
        "fee_plans_data"

    private const val FEE_INSTALLMENTS_KEY =
        "fee_installments_data"

    private const val TEACHERS_KEY =
        "teachers_data"

    private const val ATTENDANCE_KEY =
        "attendance_data"

    private const val GPS_ATTENDANCE_KEY =
        "gps_attendance_data"

    private const val NOTICES_KEY =
        "notices_data"

    private const val QUESTIONS_KEY =
        "questions_data"

    private const val TESTS_KEY =
        "tests_data"

    private const val TEST_RESULTS_KEY =
        "test_results_data"

    // =========================================================
    // APPLICATION CONTEXT
    // =========================================================

    private var appContext: Context? = null

    // =========================================================
    // INITIALIZATION
    // =========================================================

    fun init(
        context: Context
    ) {

        if (appContext == null) {

            appContext =
                context.applicationContext
        }
    }

    private fun context(): Context {

        return appContext
            ?: throw IllegalStateException(
                "SLHLocalStorage.init(context) must be called first."
            )
    }

    // =========================================================
    // ANDROID KEYSTORE
    // =========================================================

    private fun getOrCreateKey(): SecretKey {

        val keyStore =
            KeyStore.getInstance(
                KEYSTORE
            )

        keyStore.load(null)

        if (
            keyStore.containsAlias(
                KEY_ALIAS
            )
        ) {

            return keyStore.getKey(
                KEY_ALIAS,
                null
            ) as SecretKey
        }

        val keyGenerator =
            KeyGenerator.getInstance(
                KeyProperties.KEY_ALGORITHM_AES,
                KEYSTORE
            )

        val keySpec =
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or
                        KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(
                    KeyProperties.BLOCK_MODE_GCM
                )
                .setEncryptionPaddings(
                    KeyProperties.ENCRYPTION_PADDING_NONE
                )
                .setKeySize(256)
                .build()

        keyGenerator.init(
            keySpec
        )

        return keyGenerator.generateKey()
    }

    // =========================================================
    // ENCRYPT
    // =========================================================

    private fun encrypt(
        plainText: String
    ): String {

        val cipher =
            Cipher.getInstance(
                TRANSFORMATION
            )

        /*
         * IMPORTANT:
         *
         * Do not provide our own GCMParameterSpec
         * during encryption.
         *
         * Android Keystore generates the IV itself.
         */
        cipher.init(
            Cipher.ENCRYPT_MODE,
            getOrCreateKey()
        )

        /*
         * Get the IV generated by Android Keystore.
         */
        val iv =
            cipher.iv

        if (
            iv == null ||
            iv.size != IV_LENGTH
        ) {

            throw IllegalStateException(
                "Android Keystore returned an invalid AES-GCM IV."
            )
        }

        val encrypted =
            cipher.doFinal(
                plainText.toByteArray(
                    StandardCharsets.UTF_8
                )
            )

        /*
         * Stored format:
         *
         * IV + encrypted data
         */
        val combined =
            ByteArray(
                iv.size +
                        encrypted.size
            )

        System.arraycopy(
            iv,
            0,
            combined,
            0,
            iv.size
        )

        System.arraycopy(
            encrypted,
            0,
            combined,
            iv.size,
            encrypted.size
        )

        return Base64.encodeToString(
            combined,
            Base64.NO_WRAP
        )
    }

    // =========================================================
    // DECRYPT
    // =========================================================

    private fun decrypt(
        encryptedText: String
    ): String? {

        return try {

            val combined =
                Base64.decode(
                    encryptedText,
                    Base64.NO_WRAP
                )

            if (
                combined.size <= IV_LENGTH
            ) {

                return null
            }

            val iv =
                combined.copyOfRange(
                    0,
                    IV_LENGTH
                )

            val encrypted =
                combined.copyOfRange(
                    IV_LENGTH,
                    combined.size
                )

            val cipher =
                Cipher.getInstance(
                    TRANSFORMATION
                )

            val gcmSpec =
                GCMParameterSpec(
                    GCM_TAG_LENGTH,
                    iv
                )

            cipher.init(
                Cipher.DECRYPT_MODE,
                getOrCreateKey(),
                gcmSpec
            )

            val decrypted =
                cipher.doFinal(
                    encrypted
                )

            String(
                decrypted,
                StandardCharsets.UTF_8
            )

        } catch (
            e: Exception
        ) {

            null
        }
    }

    // =========================================================
    // GENERIC ENCRYPTED STORAGE
    // =========================================================

    fun save(
        key: String,
        value: String
    ) {

        val encrypted =
            encrypt(
                value
            )

        context()
            .getSharedPreferences(
                PREF_NAME,
                Context.MODE_PRIVATE
            )
            .edit()
            .putString(
                key,
                encrypted
            )
            .apply()
    }

    fun get(
        key: String
    ): String? {

        val encrypted =
            context()
                .getSharedPreferences(
                    PREF_NAME,
                    Context.MODE_PRIVATE
                )
                .getString(
                    key,
                    null
                )
                ?: return null

        return decrypt(
            encrypted
        )
    }

    fun remove(
        key: String
    ) {

        context()
            .getSharedPreferences(
                PREF_NAME,
                Context.MODE_PRIVATE
            )
            .edit()
            .remove(
                key
            )
            .apply()
    }

    fun contains(
        key: String
    ): Boolean {

        return context()
            .getSharedPreferences(
                PREF_NAME,
                Context.MODE_PRIVATE
            )
            .contains(
                key
            )
    }

    fun clearAll() {

        context()
            .getSharedPreferences(
                PREF_NAME,
                Context.MODE_PRIVATE
            )
            .edit()
            .clear()
            .apply()
    }

    // =========================================================
    // STUDENT STORAGE
    // =========================================================

    private fun studentToJson(
        student: Student
    ): JSONObject {

        return JSONObject().apply {

            put(
                "id",
                student.id
            )

            put(
                "studentId",
                student.studentId
            )

            put(
                "name",
                student.name
            )

            put(
                "mobile",
                student.mobile
            )

            put(
                "address",
                student.address
            )

            put(
                "username",
                student.username
            )

            put(
                "password",
                student.password
            )

            put(
                "course",
                student.course
            )

            put(
                "admissionDate",
                student.admissionDate
            )

            put(
                "status",
                student.status.name
            )

            put(
                "coachingId",
                student.coachingId
            )

            put(
                "batchId",
                student.batchId
            )

            put(
                "photoUri",
                student.photoUri ?: ""
            )
        }
    }

    private fun jsonToStudent(
        json: JSONObject
    ): Student {

        val status =
            try {

                AccountStatus.valueOf(
                    json.optString(
                        "status",
                        AccountStatus.APPROVED.name
                    )
                )

            } catch (
                e: Exception
            ) {

                AccountStatus.APPROVED
            }

        return Student(

            id =
                json.optString(
                    "id"
                ),

            studentId =
                json.optString(
                    "studentId"
                ),

            name =
                json.optString(
                    "name"
                ),

            mobile =
                json.optString(
                    "mobile"
                ),

            address =
                json.optString(
                    "address"
                ),

            username =
                json.optString(
                    "username"
                ),

            password =
                json.optString(
                    "password"
                ),

            course =
                json.optString(
                    "course"
                ),

            admissionDate =
                json.optString(
                    "admissionDate"
                ),

            status =
                status,

            coachingId =
                json.optString(
                    "coachingId",
                    "C001"
                ),

            batchId =
                json.optString(
                    "batchId"
                ),

            photoUri =
                json.optString(
                    "photoUri"
                ).takeIf {
                    it.isNotBlank()
                }
        )
    }

    fun saveStudents(
        students: List<Student>
    ) {

        val array =
            JSONArray()

        students.forEach { student ->

            array.put(
                studentToJson(
                    student
                )
            )
        }

        save(
            STUDENTS_KEY,
            array.toString()
        )
    }

    fun loadStudents():
            List<Student>? {

        val raw =
            get(
                STUDENTS_KEY
            )
                ?: return null

        return try {

            val array =
                JSONArray(
                    raw
                )

            val result =
                mutableListOf<Student>()

            for (
            index in 0 until array.length()
            ) {

                result.add(
                    jsonToStudent(
                        array.getJSONObject(
                            index
                        )
                    )
                )
            }

            result

        } catch (
            e: Exception
        ) {

            null
        }
    }

    // =========================================================
    // BATCH STORAGE
    // =========================================================

    private fun batchToJson(
        batch: CoachingBatch
    ): JSONObject {

        return JSONObject().apply {

            put(
                "id",
                batch.id
            )

            put(
                "coachingId",
                batch.coachingId
            )

            put(
                "name",
                batch.name
            )

            put(
                "code",
                batch.code
            )

            put(
                "course",
                batch.course
            )

            put(
                "subject",
                batch.subject
            )

            put(
                "teacherId",
                batch.teacherId
            )

            put(
                "startDate",
                batch.startDate
            )

            put(
                "endDate",
                batch.endDate
            )

            put(
                "timing",
                batch.timing
            )

            put(
                "room",
                batch.room
            )

            put(
                "description",
                batch.description
            )

            put(
                "status",
                batch.status
            )
        }
    }

    private fun jsonToBatch(
        json: JSONObject
    ): CoachingBatch {

        return CoachingBatch(

            id =
                json.optString(
                    "id"
                ),

            coachingId =
                json.optString(
                    "coachingId"
                ),

            name =
                json.optString(
                    "name"
                ),

            code =
                json.optString(
                    "code"
                ),

            course =
                json.optString(
                    "course"
                ),

            subject =
                json.optString(
                    "subject"
                ),

            teacherId =
                json.optString(
                    "teacherId"
                ),

            startDate =
                json.optString(
                    "startDate"
                ),

            endDate =
                json.optString(
                    "endDate"
                ),

            timing =
                json.optString(
                    "timing"
                ),

            room =
                json.optString(
                    "room"
                ),

            description =
                json.optString(
                    "description"
                ),

            status =
                json.optString(
                    "status",
                    "ACTIVE"
                )
        )
    }

    fun saveBatches(
        batches: List<CoachingBatch>
    ) {

        val array =
            JSONArray()

        batches.forEach { batch ->

            array.put(
                batchToJson(
                    batch
                )
            )
        }

        save(
            BATCHES_KEY,
            array.toString()
        )
    }

    fun loadBatches():
            List<CoachingBatch>? {

        val raw =
            get(
                BATCHES_KEY
            )
                ?: return null

        return try {

            val array =
                JSONArray(
                    raw
                )

            val result =
                mutableListOf<CoachingBatch>()

            for (
            index in 0 until array.length()
            ) {

                result.add(
                    jsonToBatch(
                        array.getJSONObject(
                            index
                        )
                    )
                )
            }

            result

        } catch (
            e: Exception
        ) {

            null
        }
    }

    // =========================================================
    // USER ACCOUNT STORAGE
    // =========================================================

    private fun userToJson(
        user: DemoUser
    ): JSONObject {

        return JSONObject().apply {

            put(
                "id",
                user.id
            )

            put(
                "username",
                user.username
            )

            put(
                "password",
                user.password
            )

            put(
                "role",
                user.role.name
            )

            put(
                "status",
                user.status.name
            )

            put(
                "coachingId",
                user.coachingId ?: ""
            )

            put(
                "displayName",
                user.displayName
            )
        }
    }

    private fun jsonToUser(
        json: JSONObject
    ): DemoUser {

        val role =
            try {

                UserRole.valueOf(
                    json.optString(
                        "role",
                        UserRole.STUDENT.name
                    )
                )

            } catch (
                e: Exception
            ) {

                UserRole.STUDENT
            }

        val status =
            try {

                AccountStatus.valueOf(
                    json.optString(
                        "status",
                        AccountStatus.APPROVED.name
                    )
                )

            } catch (
                e: Exception
            ) {

                AccountStatus.APPROVED
            }

        return DemoUser(

            id =
                json.optString(
                    "id"
                ),

            username =
                json.optString(
                    "username"
                ),

            password =
                json.optString(
                    "password"
                ),

            role =
                role,

            status =
                status,

            coachingId =
                json.optString(
                    "coachingId"
                ).takeIf {
                    it.isNotBlank()
                },

            displayName =
                json.optString(
                    "displayName"
                )
        )
    }

    fun saveUserAccounts(
        users: List<DemoUser>
    ) {

        val array =
            JSONArray()

        users.forEach { user ->

            array.put(
                userToJson(
                    user
                )
            )
        }

        save(
            USERS_KEY,
            array.toString()
        )
    }

    fun loadUserAccounts():
            List<DemoUser>? {

        val raw =
            get(
                USERS_KEY
            )
                ?: return null

        return try {

            val array =
                JSONArray(
                    raw
                )

            val result =
                mutableListOf<DemoUser>()

            for (
            index in 0 until array.length()
            ) {

                result.add(
                    jsonToUser(
                        array.getJSONObject(
                            index
                        )
                    )
                )
            }

            result

        } catch (
            e: Exception
        ) {

            null
        }
    }

    // =========================================================
    // COACHING PROFILE STORAGE
    // =========================================================

    private fun coachingProfileToJson(
        profile: CoachingProfile
    ): JSONObject {

        return JSONObject().apply {

            put(
                "id",
                profile.id
            )

            put(
                "name",
                profile.name
            )

            put(
                "shortName",
                profile.shortName
            )

            put(
                "tagline",
                profile.tagline
            )

            put(
                "logoUri",
                profile.logoUri ?: ""
            )

            put(
                "phone",
                profile.phone
            )

            put(
                "email",
                profile.email
            )

            put(
                "address",
                profile.address
            )

            if (
                profile.latitude != null
            ) {

                put(
                    "latitude",
                    profile.latitude
                )
            }

            if (
                profile.longitude != null
            ) {

                put(
                    "longitude",
                    profile.longitude
                )
            }

            put(
                "attendanceRadiusMeters",
                profile.attendanceRadiusMeters
                    .toDouble()
            )
        }
    }

    private fun jsonToCoachingProfile(
        json: JSONObject
    ): CoachingProfile {

        val latitude =
            if (
                json.has("latitude") &&
                !json.isNull("latitude")
            ) {

                json.optDouble(
                    "latitude"
                )

            } else {

                null
            }

        val longitude =
            if (
                json.has("longitude") &&
                !json.isNull("longitude")
            ) {

                json.optDouble(
                    "longitude"
                )

            } else {

                null
            }

        return CoachingProfile(

            id =
                json.optString(
                    "id"
                ),

            name =
                json.optString(
                    "name"
                ),

            shortName =
                json.optString(
                    "shortName"
                ),

            tagline =
                json.optString(
                    "tagline"
                ),

            logoUri =
                json.optString(
                    "logoUri"
                ).takeIf {
                    it.isNotBlank()
                },

            phone =
                json.optString(
                    "phone"
                ),

            email =
                json.optString(
                    "email"
                ),

            address =
                json.optString(
                    "address"
                ),

            latitude =
                latitude,

            longitude =
                longitude,

            attendanceRadiusMeters =
                json.optDouble(
                    "attendanceRadiusMeters",
                    100.0
                ).toFloat()
        )
    }

    fun saveCoachingProfiles(
        profiles: List<CoachingProfile>
    ) {

        val array =
            JSONArray()

        profiles.forEach { profile ->

            array.put(
                coachingProfileToJson(
                    profile
                )
            )
        }

        save(
            COACHING_PROFILES_KEY,
            array.toString()
        )
    }

    fun loadCoachingProfiles():
            List<CoachingProfile>? {

        val raw =
            get(
                COACHING_PROFILES_KEY
            )
                ?: return null

        return try {

            val array =
                JSONArray(
                    raw
                )

            val result =
                mutableListOf<CoachingProfile>()

            for (
            index in 0 until array.length()
            ) {

                result.add(
                    jsonToCoachingProfile(
                        array.getJSONObject(
                            index
                        )
                    )
                )
            }

            result

        } catch (
            e: Exception
        ) {

            null
        }
    }

    // =========================================================
    // PAYMENT STORAGE
    // =========================================================

    private fun paymentToJson(
        payment: PaymentRecord
    ): JSONObject {

        return JSONObject().apply {

            put(
                "id",
                payment.id
            )

            put(
                "receiptNumber",
                payment.receiptNumber
            )

            put(
                "coachingId",
                payment.coachingId
            )

            put(
                "studentId",
                payment.studentId
            )

            put(
                "batchId",
                payment.batchId
            )

            put(
                "installmentId",
                payment.installmentId
            )

            put(
                "studentName",
                payment.studentName
            )

            put(
                "studentCode",
                payment.studentCode
            )

            put(
                "course",
                payment.course
            )

            put(
                "batchName",
                payment.batchName
            )

            put(
                "amount",
                payment.amount
            )

            put(
                "paymentDate",
                payment.paymentDate
            )

            put(
                "paymentMode",
                payment.paymentMode.name
            )

            put(
                "transactionReference",
                payment.transactionReference
            )

            put(
                "previousPaidAmount",
                payment.previousPaidAmount
            )

            put(
                "totalFee",
                payment.totalFee
            )

            put(
                "remainingAmount",
                payment.remainingAmount
            )

            put(
                "remark",
                payment.remark
            )

            put(
                "status",
                payment.status.name
            )

            put(
                "createdAt",
                payment.createdAt
            )
        }
    }

    private fun jsonToPayment(
        json: JSONObject
    ): PaymentRecord {

        val paymentMode =
            try {

                PaymentMode.valueOf(
                    json.optString(
                        "paymentMode",
                        PaymentMode.OTHER.name
                    )
                )

            } catch (
                e: Exception
            ) {

                PaymentMode.OTHER
            }

        val status =
            try {

                PaymentStatus.valueOf(
                    json.optString(
                        "status",
                        PaymentStatus.VERIFIED.name
                    )
                )

            } catch (
                e: Exception
            ) {

                PaymentStatus.VERIFIED
            }

        return PaymentRecord(

            id =
                json.optString(
                    "id"
                ),

            receiptNumber =
                json.optString(
                    "receiptNumber"
                ),

            coachingId =
                json.optString(
                    "coachingId"
                ),

            studentId =
                json.optString(
                    "studentId"
                ),

            batchId =
                json.optString(
                    "batchId"
                ),

            installmentId =
                json.optString(
                    "installmentId"
                ),

            studentName =
                json.optString(
                    "studentName"
                ),

            studentCode =
                json.optString(
                    "studentCode"
                ),

            course =
                json.optString(
                    "course"
                ),

            batchName =
                json.optString(
                    "batchName"
                ),

            amount =
                json.optDouble(
                    "amount",
                    0.0
                ),

            paymentDate =
                json.optString(
                    "paymentDate"
                ),

            paymentMode =
                paymentMode,

            transactionReference =
                json.optString(
                    "transactionReference"
                ),

            previousPaidAmount =
                json.optDouble(
                    "previousPaidAmount",
                    0.0
                ),

            totalFee =
                json.optDouble(
                    "totalFee",
                    0.0
                ),

            remainingAmount =
                json.optDouble(
                    "remainingAmount",
                    0.0
                ),

            remark =
                json.optString(
                    "remark"
                ),

            status =
                status,

            createdAt =
                json.optLong(
                    "createdAt",
                    System.currentTimeMillis()
                )
        )
    }

    fun savePayments(
        payments: List<PaymentRecord>
    ) {

        val array =
            JSONArray()

        payments.forEach { payment ->

            array.put(
                paymentToJson(
                    payment
                )
            )
        }

        save(
            PAYMENTS_KEY,
            array.toString()
        )
    }

    fun loadPayments():
            List<PaymentRecord>? {

        val raw =
            get(
                PAYMENTS_KEY
            )
                ?: return null

        return try {

            val array =
                JSONArray(
                    raw
                )

            val result =
                mutableListOf<PaymentRecord>()

            for (
            index in 0 until array.length()
            ) {

                result.add(
                    jsonToPayment(
                        array.getJSONObject(
                            index
                        )
                    )
                )
            }

            result

        } catch (
            e: Exception
        ) {

            null
        }
    }

    // =========================================================
    // FEE PLANS + INSTALLMENTS
    // =========================================================

    private fun feePlanToJson(
        plan: StudentFeePlan
    ): JSONObject {

        return JSONObject().apply {
            put("studentId", plan.studentId)
            put("coachingId", plan.coachingId)
            put("originalFee", plan.originalFee)
            put("concessionType", plan.concessionType.name)
            put("concessionValue", plan.concessionValue)
            put("concessionAmount", plan.concessionAmount)
            put("finalFee", plan.finalFee)
            put("paymentMode", plan.paymentMode.name)
        }
    }

    private fun jsonToFeePlan(
        json: JSONObject
    ): StudentFeePlan {

        return StudentFeePlan(
            studentId = json.optString("studentId", ""),
            coachingId = json.optString("coachingId", ""),
            originalFee = json.optDouble("originalFee", 0.0),
            concessionType = try {
                FeeConcessionType.valueOf(
                    json.optString("concessionType", FeeConcessionType.NONE.name)
                )
            } catch (_: Exception) {
                FeeConcessionType.NONE
            },
            concessionValue = json.optDouble("concessionValue", 0.0),
            concessionAmount = json.optDouble("concessionAmount", 0.0),
            finalFee = json.optDouble("finalFee", 0.0),
            paymentMode = try {
                FeePaymentMode.valueOf(
                    json.optString("paymentMode", FeePaymentMode.INSTALLMENTS.name)
                )
            } catch (_: Exception) {
                FeePaymentMode.INSTALLMENTS
            }
        )
    }

    private fun feeInstallmentToJson(
        installment: FeeInstallment
    ): JSONObject {

        return JSONObject().apply {
            put("id", installment.id)
            put("studentId", installment.studentId)
            put("coachingId", installment.coachingId)
            put("installmentNumber", installment.installmentNumber)
            put("amount", installment.amount)
            put("paidAmount", installment.paidAmount)
            put("dueDate", installment.dueDate)
            put("paidDate", installment.paidDate)
            put("status", installment.status.name)
            put("paymentNote", installment.paymentNote)
        }
    }

    private fun jsonToFeeInstallment(
        json: JSONObject
    ): FeeInstallment {

        return FeeInstallment(
            id = json.optString("id", ""),
            studentId = json.optString("studentId", ""),
            coachingId = json.optString("coachingId", ""),
            installmentNumber = json.optInt("installmentNumber", 0),
            amount = json.optDouble("amount", 0.0),
            paidAmount = json.optDouble("paidAmount", 0.0),
            dueDate = json.optString("dueDate", ""),
            paidDate = json.optString("paidDate", ""),
            status = try {
                FeeInstallmentStatus.valueOf(
                    json.optString("status", FeeInstallmentStatus.PENDING.name)
                )
            } catch (_: Exception) {
                FeeInstallmentStatus.PENDING
            },
            paymentNote = json.optString("paymentNote", "")
        )
    }

    fun saveFeePlans(
        plans: List<StudentFeePlan>
    ) {
        val array = JSONArray()
        plans.forEach { array.put(feePlanToJson(it)) }
        save(FEE_PLANS_KEY, array.toString())
    }

    fun loadFeePlans(): List<StudentFeePlan>? {
        val raw = get(FEE_PLANS_KEY) ?: return null
        return try {
            val array = JSONArray(raw)
            val result = mutableListOf<StudentFeePlan>()
            for (index in 0 until array.length()) {
                result.add(jsonToFeePlan(array.getJSONObject(index)))
            }
            result
        } catch (_: Exception) {
            null
        }
    }

    fun saveFeeInstallments(
        installments: List<FeeInstallment>
    ) {
        val array = JSONArray()
        installments.forEach { array.put(feeInstallmentToJson(it)) }
        save(FEE_INSTALLMENTS_KEY, array.toString())
    }

    fun loadFeeInstallments(): List<FeeInstallment>? {
        val raw = get(FEE_INSTALLMENTS_KEY) ?: return null
        return try {
            val array = JSONArray(raw)
            val result = mutableListOf<FeeInstallment>()
            for (index in 0 until array.length()) {
                result.add(jsonToFeeInstallment(array.getJSONObject(index)))
            }
            result
        } catch (_: Exception) {
            null
        }
    }

    // =========================================================
    // TEACHERS
    // =========================================================

    private fun teacherToJson(
        teacher: Teacher
    ): JSONObject {

        val obj =
            JSONObject()

        obj.put(
            "id",
            teacher.id
        )

        obj.put(
            "coachingId",
            teacher.coachingId
        )

        obj.put(
            "name",
            teacher.name
        )

        obj.put(
            "mobile",
            teacher.mobile
        )

        obj.put(
            "email",
            teacher.email
        )

        obj.put(
            "address",
            teacher.address
        )

        obj.put(
            "subject",
            teacher.subject
        )

        obj.put(
            "qualification",
            teacher.qualification
        )

        obj.put(
            "username",
            teacher.username
        )

        obj.put(
            "password",
            teacher.password
        )

        obj.put(
            "joiningDate",
            teacher.joiningDate
        )

        obj.put(
            "accountStatus",
            teacher.accountStatus
        )

        return obj
    }

    private fun jsonToTeacher(
        json: JSONObject
    ): Teacher {

        return Teacher(
            id =
                json.optString(
                    "id"
                ),

            coachingId =
                json.optString(
                    "coachingId"
                ),

            name =
                json.optString(
                    "name"
                ),

            mobile =
                json.optString(
                    "mobile"
                ),

            email =
                json.optString(
                    "email"
                ),

            address =
                json.optString(
                    "address"
                ),

            subject =
                json.optString(
                    "subject"
                ),

            qualification =
                json.optString(
                    "qualification"
                ),

            username =
                json.optString(
                    "username"
                ),

            password =
                json.optString(
                    "password"
                ),

            joiningDate =
                json.optString(
                    "joiningDate"
                ),

            accountStatus =
                json.optString(
                    "accountStatus",
                    "ACTIVE"
                )
        )
    }

    fun saveTeachers(
        teachers: List<Teacher>
    ) {

        val array =
            JSONArray()

        teachers.forEach { teacher ->

            array.put(
                teacherToJson(
                    teacher
                )
            )
        }

        save(
            TEACHERS_KEY,
            array.toString()
        )
    }

    fun loadTeachers():
            List<Teacher>? {

        val raw =
            get(
                TEACHERS_KEY
            )
                ?: return null

        return try {

            val array =
                JSONArray(
                    raw
                )

            val result =
                mutableListOf<Teacher>()

            for (
            index in 0 until array.length()
            ) {

                result.add(
                    jsonToTeacher(
                        array.getJSONObject(
                            index
                        )
                    )
                )
            }

            result

        } catch (
            e: Exception
        ) {

            null
        }
    }

    // =========================================================
    // ATTENDANCE (manual absent/present overrides)
    // =========================================================

    private fun attendanceToJson(
        record: ManualAttendanceRecord
    ): JSONObject {

        val obj = JSONObject()

        obj.put("id", record.id)
        obj.put("studentId", record.studentId)
        obj.put("coachingId", record.coachingId)
        obj.put("date", record.date)
        obj.put("status", record.status.name)

        return obj
    }

    private fun jsonToAttendance(
        json: JSONObject
    ): ManualAttendanceRecord {

        val statusName =
            json.optString(
                "status",
                "ABSENT"
            )

        return ManualAttendanceRecord(
            id = json.optString("id"),
            studentId = json.optString("studentId"),
            coachingId = json.optString("coachingId"),
            date = json.optString("date"),
            status =
                try {
                    ManualAttendanceStatus.valueOf(
                        statusName
                    )
                } catch (e: Exception) {
                    ManualAttendanceStatus.ABSENT
                }
        )
    }

    fun saveAttendanceRecords(
        records: List<ManualAttendanceRecord>
    ) {

        val array = JSONArray()

        records.forEach {
            array.put(attendanceToJson(it))
        }

        save(ATTENDANCE_KEY, array.toString())
    }

    fun loadAttendanceRecords():
            List<ManualAttendanceRecord>? {

        val raw =
            get(ATTENDANCE_KEY)
                ?: return null

        return try {

            val array = JSONArray(raw)
            val result =
                mutableListOf<ManualAttendanceRecord>()

            for (index in 0 until array.length()) {
                result.add(
                    jsonToAttendance(
                        array.getJSONObject(index)
                    )
                )
            }

            result

        } catch (e: Exception) {
            null
        }
    }

    // =========================================================
    // GPS ATTENDANCE
    // =========================================================

    private fun gpsAttendanceToJson(
        record: GpsAttendanceRecord
    ): JSONObject {

        val obj = JSONObject()

        obj.put("id", record.id)
        obj.put("studentId", record.studentId)
        obj.put("coachingId", record.coachingId)
        obj.put("date", record.date)
        obj.put("time", record.time)
        obj.put("latitude", record.latitude)
        obj.put("longitude", record.longitude)
        obj.put("distanceMeters", record.distanceMeters.toDouble())

        return obj
    }

    private fun jsonToGpsAttendance(
        json: JSONObject
    ): GpsAttendanceRecord {

        return GpsAttendanceRecord(
            id = json.optString("id"),
            studentId = json.optString("studentId"),
            coachingId = json.optString("coachingId"),
            date = json.optString("date"),
            time = json.optString("time"),
            latitude = json.optDouble("latitude", 0.0),
            longitude = json.optDouble("longitude", 0.0),
            distanceMeters =
                json.optDouble("distanceMeters", 0.0).toFloat()
        )
    }

    fun saveGpsAttendanceRecords(
        records: List<GpsAttendanceRecord>
    ) {

        val array = JSONArray()

        records.forEach {
            array.put(gpsAttendanceToJson(it))
        }

        save(GPS_ATTENDANCE_KEY, array.toString())
    }

    fun loadGpsAttendanceRecords():
            List<GpsAttendanceRecord>? {

        val raw =
            get(GPS_ATTENDANCE_KEY)
                ?: return null

        return try {

            val array = JSONArray(raw)
            val result =
                mutableListOf<GpsAttendanceRecord>()

            for (index in 0 until array.length()) {
                result.add(
                    jsonToGpsAttendance(
                        array.getJSONObject(index)
                    )
                )
            }

            result

        } catch (e: Exception) {
            null
        }
    }

    // =========================================================
    // NOTICES
    // =========================================================

    private fun noticeToJson(
        notice: CoachingNotice
    ): JSONObject {

        val obj = JSONObject()

        obj.put("id", notice.id)
        obj.put("coachingId", notice.coachingId)
        obj.put("batchId", notice.batchId)
        obj.put("title", notice.title)
        obj.put("message", notice.message)
        obj.put("noticeDate", notice.noticeDate)
        obj.put("expiryDate", notice.expiryDate)
        obj.put("createdById", notice.createdById)
        obj.put("createdByName", notice.createdByName)
        obj.put("status", notice.status.name)

        val readArray = JSONArray()
        notice.readByUserIds.forEach {
            readArray.put(it)
        }
        obj.put("readByUserIds", readArray)

        return obj
    }

    private fun jsonToNotice(
        json: JSONObject
    ): CoachingNotice {

        val statusName =
            json.optString("status", "ACTIVE")

        val readIds = mutableListOf<String>()
        val readArray = json.optJSONArray("readByUserIds")
        if (readArray != null) {
            for (i in 0 until readArray.length()) {
                readIds.add(readArray.optString(i))
            }
        }

        return CoachingNotice(
            id = json.optString("id"),
            coachingId = json.optString("coachingId"),
            batchId = json.optString("batchId"),
            title = json.optString("title"),
            message = json.optString("message"),
            noticeDate = json.optString("noticeDate"),
            expiryDate = json.optString("expiryDate"),
            createdById = json.optString("createdById"),
            createdByName = json.optString("createdByName"),
            status =
                try {
                    NoticeStatus.valueOf(statusName)
                } catch (e: Exception) {
                    NoticeStatus.ACTIVE
                },
            readByUserIds = readIds
        )
    }

    fun saveNotices(
        notices: List<CoachingNotice>
    ) {

        val array = JSONArray()

        notices.forEach {
            array.put(noticeToJson(it))
        }

        save(NOTICES_KEY, array.toString())
    }

    fun loadNotices(): List<CoachingNotice>? {

        val raw =
            get(NOTICES_KEY)
                ?: return null

        return try {

            val array = JSONArray(raw)
            val result = mutableListOf<CoachingNotice>()

            for (index in 0 until array.length()) {
                result.add(
                    jsonToNotice(
                        array.getJSONObject(index)
                    )
                )
            }

            result

        } catch (e: Exception) {
            null
        }
    }

    // =========================================================
    // QUESTIONS
    // =========================================================

    private fun questionToJson(
        question: TestQuestion
    ): JSONObject {

        val obj = JSONObject()

        obj.put("id", question.id)
        obj.put("testId", question.testId)
        obj.put("coachingId", question.coachingId)
        obj.put("batchId", question.batchId)
        obj.put("questionText", question.questionText)
        obj.put("optionA", question.optionA)
        obj.put("optionB", question.optionB)
        obj.put("optionC", question.optionC)
        obj.put("optionD", question.optionD)
        obj.put("correctOption", question.correctOption)
        obj.put("marks", question.marks)
        obj.put("questionType", question.questionType.name)
        obj.put("questionOrder", question.questionOrder)

        return obj
    }

    private fun jsonToQuestion(
        json: JSONObject
    ): TestQuestion {

        val typeName =
            json.optString("questionType", "MCQ")

        return TestQuestion(
            id = json.optString("id"),
            testId = json.optString("testId"),
            coachingId = json.optString("coachingId"),
            batchId = json.optString("batchId"),
            questionText = json.optString("questionText"),
            optionA = json.optString("optionA"),
            optionB = json.optString("optionB"),
            optionC = json.optString("optionC"),
            optionD = json.optString("optionD"),
            correctOption = json.optString("correctOption"),
            marks = json.optDouble("marks", 1.0),
            questionType =
                try {
                    QuestionType.valueOf(typeName)
                } catch (e: Exception) {
                    QuestionType.MCQ
                },
            questionOrder = json.optInt("questionOrder", 0)
        )
    }

    fun saveQuestions(
        questions: List<TestQuestion>
    ) {

        val array = JSONArray()

        questions.forEach {
            array.put(questionToJson(it))
        }

        save(QUESTIONS_KEY, array.toString())
    }

    fun loadQuestions(): List<TestQuestion>? {

        val raw =
            get(QUESTIONS_KEY)
                ?: return null

        return try {

            val array = JSONArray(raw)
            val result = mutableListOf<TestQuestion>()

            for (index in 0 until array.length()) {
                result.add(
                    jsonToQuestion(
                        array.getJSONObject(index)
                    )
                )
            }

            result

        } catch (e: Exception) {
            null
        }
    }

    // =========================================================
    // TESTS
    // =========================================================

    private fun testToJson(
        test: CoachingTest
    ): JSONObject {

        val obj = JSONObject()

        obj.put("id", test.id)
        obj.put("coachingId", test.coachingId)
        obj.put("batchId", test.batchId)
        obj.put("title", test.title)
        obj.put("subject", test.subject)
        obj.put("testDate", test.testDate)
        obj.put("totalMarks", test.totalMarks)
        obj.put("passingMarks", test.passingMarks)
        obj.put("description", test.description)
        obj.put("createdById", test.createdById)
        obj.put("createdByName", test.createdByName)
        obj.put("status", test.status.name)
        obj.put("testType", test.testType.name)
        obj.put("durationMinutes", test.durationMinutes)
        obj.put("startTime", test.startTime)
        obj.put("endTime", test.endTime)
        obj.put("rejectionReason", test.rejectionReason)
        obj.put("submittedAt", test.submittedAt)
        obj.put("approvedAt", test.approvedAt)
        obj.put("approvedById", test.approvedById)
        obj.put("approvedByName", test.approvedByName)

        return obj
    }

    private fun jsonToTest(
        json: JSONObject
    ): CoachingTest {

        return CoachingTest(
            id = json.optString("id"),
            coachingId = json.optString("coachingId"),
            batchId = json.optString("batchId"),
            title = json.optString("title"),
            subject = json.optString("subject"),
            testDate = json.optString("testDate"),
            totalMarks = json.optDouble("totalMarks", 0.0),
            passingMarks = json.optDouble("passingMarks", 0.0),
            description = json.optString("description"),
            createdById = json.optString("createdById"),
            createdByName = json.optString("createdByName"),
            status = parseTestStatus(json.optString("status", "ACTIVE")),
            testType = parseTestType(json.optString("testType", "QUIZ")),
            durationMinutes = json.optInt("durationMinutes", 0),
            startTime = json.optString("startTime", ""),
            endTime = json.optString("endTime", ""),
            rejectionReason = json.optString("rejectionReason", ""),
            submittedAt = json.optString("submittedAt", ""),
            approvedAt = json.optString("approvedAt", ""),
            approvedById = json.optString("approvedById", ""),
            approvedByName = json.optString("approvedByName", "")
        )
    }

    fun saveTests(
        tests: List<CoachingTest>
    ) {

        val array = JSONArray()

        tests.forEach {
            array.put(testToJson(it))
        }

        save(TESTS_KEY, array.toString())
    }

    fun loadTests(): List<CoachingTest>? {

        val raw =
            get(TESTS_KEY)
                ?: return null

        return try {

            val array = JSONArray(raw)
            val result = mutableListOf<CoachingTest>()

            for (index in 0 until array.length()) {
                result.add(
                    jsonToTest(
                        array.getJSONObject(index)
                    )
                )
            }

            result

        } catch (e: Exception) {
            null
        }
    }

    // =========================================================
    // TEST RESULTS
    // =========================================================

    private fun testResultToJson(
        result: TestResult
    ): JSONObject {

        val obj = JSONObject()

        obj.put("id", result.id)
        obj.put("testId", result.testId)
        obj.put("studentId", result.studentId)
        obj.put("coachingId", result.coachingId)
        obj.put("obtainedMarks", result.obtainedMarks)
        obj.put("remarks", result.remarks)
        obj.put("resultDate", result.resultDate)
        obj.put("status", result.status)

        return obj
    }

    private fun jsonToTestResult(
        json: JSONObject
    ): TestResult {

        return TestResult(
            id = json.optString("id"),
            testId = json.optString("testId"),
            studentId = json.optString("studentId"),
            coachingId = json.optString("coachingId"),
            obtainedMarks = json.optDouble("obtainedMarks", 0.0),
            remarks = json.optString("remarks"),
            resultDate = json.optString("resultDate"),
            status = json.optString("status", "PUBLISHED")
        )
    }

    fun saveTestResults(
        results: List<TestResult>
    ) {

        val array = JSONArray()

        results.forEach {
            array.put(testResultToJson(it))
        }

        save(TEST_RESULTS_KEY, array.toString())
    }

    fun loadTestResults(): List<TestResult>? {

        val raw =
            get(TEST_RESULTS_KEY)
                ?: return null

        return try {

            val array = JSONArray(raw)
            val result = mutableListOf<TestResult>()

            for (index in 0 until array.length()) {
                result.add(
                    jsonToTestResult(
                        array.getJSONObject(index)
                    )
                )
            }

            result

        } catch (e: Exception) {
            null
        }
    }
}
